import { Product, ProductsResponse } from '@/types/product'

// Fake product data generator
export const FAKE_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Premium Wireless Headphones',
    description: 'High-quality wireless headphones with noise cancellation and 30-hour battery life. Perfect for music lovers and professionals.',
    price: 299.99,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&h=500&fit=crop',
    category: 'Electronics',
    stock: 45,
    rating: 4.8,
    reviews: 234,
  },
  {
    id: '2',
    name: 'Slim Fit Cotton T-Shirt',
    description: 'Comfortable and breathable cotton t-shirt available in multiple colors. Perfect for casual everyday wear.',
    price: 29.99,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop',
    category: 'Clothing',
    stock: 120,
    rating: 4.5,
    reviews: 89,
  },
  {
    id: '3',
    name: 'Smart Watch Series 5',
    description: 'Advanced smartwatch with health tracking, GPS, and water resistance. Stay connected and track your fitness goals.',
    price: 399.99,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=500&fit=crop',
    category: 'Electronics',
    stock: 67,
    rating: 4.7,
    reviews: 456,
  },
  {
    id: '4',
    name: 'Leather Messenger Bag',
    description: 'Stylish genuine leather messenger bag with multiple compartments. Perfect for work or travel.',
    price: 149.99,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&h=500&fit=crop',
    category: 'Accessories',
    stock: 34,
    rating: 4.6,
    reviews: 127,
  },
  {
    id: '5',
    name: 'Running Shoes Pro',
    description: 'Professional running shoes with advanced cushioning and support. Engineered for performance and comfort.',
    price: 129.99,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop',
    category: 'Footwear',
    stock: 88,
    rating: 4.9,
    reviews: 312,
  },
  {
    id: '6',
    name: 'Portable Bluetooth Speaker',
    description: 'Compact waterproof speaker with 360-degree sound. Perfect for outdoor adventures and parties.',
    price: 79.99,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500&h=500&fit=crop',
    category: 'Electronics',
    stock: 156,
    rating: 4.4,
    reviews: 178,
  },
  {
    id: '7',
    name: 'Denim Jacket',
    description: 'Classic denim jacket with a modern fit. A timeless piece for any wardrobe.',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500&h=500&fit=crop',
    category: 'Clothing',
    stock: 52,
    rating: 4.3,
    reviews: 94,
  },
  {
    id: '8',
    name: 'Yoga Mat Premium',
    description: 'Extra thick non-slip yoga mat with carrying strap. Perfect for yoga, pilates, and floor exercises.',
    price: 49.99,
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500&h=500&fit=crop',
    category: 'Fitness',
    stock: 203,
    rating: 4.7,
    reviews: 267,
  },
  {
    id: '9',
    name: 'Stainless Steel Water Bottle',
    description: 'Insulated water bottle that keeps drinks cold for 24 hours or hot for 12 hours. BPA-free and eco-friendly.',
    price: 34.99,
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=500&h=500&fit=crop',
    category: 'Accessories',
    stock: 340,
    rating: 4.8,
    reviews: 445,
  },
  {
    id: '10',
    name: 'Wireless Gaming Mouse',
    description: 'High-precision wireless gaming mouse with customizable RGB lighting and programmable buttons.',
    price: 69.99,
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500&h=500&fit=crop',
    category: 'Electronics',
    stock: 98,
    rating: 4.6,
    reviews: 189,
  },
  {
    id: '11',
    name: 'Sunglasses Aviator',
    description: 'Classic aviator sunglasses with UV protection and polarized lenses. Stylish and protective.',
    price: 119.99,
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500&h=500&fit=crop',
    category: 'Accessories',
    stock: 76,
    rating: 4.5,
    reviews: 156,
  },
  {
    id: '12',
    name: 'Backpack Travel Pro',
    description: 'Durable travel backpack with laptop compartment and USB charging port. Perfect for commuters and travelers.',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&h=500&fit=crop',
    category: 'Accessories',
    stock: 112,
    rating: 4.7,
    reviews: 289,
  },
]

export function getFakeProducts(storeId?: string): ProductsResponse {
  // Simulate API response structure
  return {
    data: FAKE_PRODUCTS,
    total: FAKE_PRODUCTS.length,
  }
}

export function getFakeProductById(id: string): Product | undefined {
  return FAKE_PRODUCTS.find(product => product.id === id)
}
